#!/usr/bin/env bash
# Entrypoint for the spec-issue workflow. Sources the helper libraries and
# loops over the eligible issue numbers, producing a spec branch + draft PR
# + issue comment per issue. Per-issue failures are logged and do not abort
# the entire run.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "${SCRIPT_DIR}/slug.sh"
source "${SCRIPT_DIR}/call_claude.sh"
source "${SCRIPT_DIR}/resolve_targets.sh"
source "${SCRIPT_DIR}/build_bundle.sh"

push_spec_and_pr() {
  local n="$1"
  local spec_src="$2"
  local discovery_src="$3"

  local title slug_str branch spec_path today_date default_branch
  title=$(gh issue view "$n" --json title -q .title)
  slug_str=$(slug "$title")
  branch="spec/issue-${n}-${slug_str}"
  today_date=$(date -u +%Y-%m-%d)
  spec_path="docs/superpowers/specs/${today_date}-issue-${n}-${slug_str}-design.md"
  default_branch=$(gh repo view --json defaultBranchRef -q .defaultBranchRef.name)

  git checkout -b "$branch"
  mkdir -p "$(dirname "$spec_path")"
  cp "$spec_src" "$spec_path"
  git add "$spec_path"
  git commit -m "spec: draft for issue #${n}"
  git push -u origin "$branch"

  local pr_body
  pr_body=$(printf '%s\n\nRefs #%s\n\n---\n*Generated by spec-issue workflow. Review before merge.*\n' \
              "$(cat "$discovery_src")" "$n")

  local pr_url
  pr_url=$(gh pr create \
    --draft \
    --title "Spec: ${title} (#${n})" \
    --body "$pr_body" \
    --base "$default_branch" \
    | tail -n 1)

  gh issue comment "$n" --body "Spec PR opened: ${pr_url}" \
    || echo "::warning::issue comment failed for #${n}; PR is the canonical artifact"

  # Return to the default branch so the next issue starts from a clean state.
  git checkout "$default_branch"
}

main() {
  local targets
  targets=$(resolve_targets "${ISSUE_NUMBER:-}")
  if [[ -z "$targets" ]]; then
    echo "::notice::no eligible issues — nothing to do"
    return 0
  fi

  local processed=0 failed=0 issue_number
  for issue_number in $targets; do
    echo "::group::issue #${issue_number}"

    if remote_spec_branch_exists "$issue_number"; then
      echo "::notice::skipped #${issue_number} (branch exists)"
      echo "::endgroup::"
      continue
    fi

    local bundle raw_response tmp_spec tmp_discovery
    tmp_spec=$(mktemp)
    tmp_discovery=$(mktemp)

    if ! bundle=$(build_bundle "$issue_number"); then
      echo "::error::build_bundle failed for #${issue_number}"
      failed=$((failed + 1))
      rm -f "$tmp_spec" "$tmp_discovery"
      echo "::endgroup::"
      continue
    fi

    if ! raw_response=$(call_claude "$bundle"); then
      echo "::error::call_claude failed for #${issue_number}"
      failed=$((failed + 1))
      rm -f "$tmp_spec" "$tmp_discovery"
      echo "::endgroup::"
      continue
    fi

    if ! parse_response "$raw_response" "$tmp_spec" "$tmp_discovery"; then
      echo "::error::delimiter parsing failed for issue #${issue_number}"
      printf '%s' "$raw_response" > "/tmp/raw-${issue_number}.txt"
      failed=$((failed + 1))
      rm -f "$tmp_spec" "$tmp_discovery"
      echo "::endgroup::"
      continue
    fi

    if ! push_spec_and_pr "$issue_number" "$tmp_spec" "$tmp_discovery"; then
      echo "::error::push/PR failed for #${issue_number}"
      failed=$((failed + 1))
      rm -f "$tmp_spec" "$tmp_discovery"
      echo "::endgroup::"
      continue
    fi

    rm -f "$tmp_spec" "$tmp_discovery"
    processed=$((processed + 1))
    echo "::endgroup::"
  done

  echo "processed=${processed} failed=${failed}"
  [[ $failed -eq 0 ]]
}

main "$@"
